name: Update Dependency Graph
on:
  push:
    branches: ["master", "main", "dev"]
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v3